In [1]:
using LinearAlgebra

In [144]:
A = randn(21, 21) + randn(21, 21)*im
x = randn(21) + randn(21)*im
x = x/norm(x)

21-element Vector{ComplexF64}:
 -0.030883112758387694 - 0.30381425194296674im
  -0.09394927450781025 - 0.2069450865694823im
   0.09461901254891787 - 0.21345587576024527im
  -0.18301807726133396 + 0.09571987584219226im
   0.11296291995759218 + 0.036642771396103516im
  -0.08688918102193971 - 0.10070418768995115im
   0.19442973141692108 + 0.22981490920928604im
  -0.01284971357516829 + 0.05978763550701729im
  -0.26381608894855885 - 0.022726395026796926im
  -0.10483537612715892 - 0.3244877439900397im
  0.012635451747302967 + 0.03225506168884614im
  -0.03310110576693626 - 0.09411163484002302im
  -0.20429773245919305 - 0.14090689602575052im
   -0.2500771849895509 - 0.06157192505135514im
    0.0911437986942489 - 0.10928821599631466im
  -0.20152411464528117 - 0.10007519385401929im
   -0.3037806572254514 - 0.2179091310920153im
  -0.05212116429365226 + 0.04488944090079143im
   0.12856861567255293 + 0.17441569531262116im
  -0.03359974347007039 + 0.15275231117731908im
   0.08437947525194964 + 0.111

In [171]:
#### Power Method

function power(A, x, eps)

    lambda = 0
    e = 1.0
    t = 0
    
    while (e > eps && t < 1000)
        t = t + 1
        y = A*x
        x = y/norm(y)
        lambda1 = lambda
        lambda = x'*y

        # Erro
        e = abs(lambda1 - lambda)
    end
    return lambda
end

power (generic function with 5 methods)

In [172]:
power(A, x, 1e-8)

5.6013345391877705 + 0.0im

In [173]:
##### Comparando autovalores
sort(abs.(eigen(A).values))

21-element Vector{Float64}:
 0.28388985975653847
 1.080058108737448
 1.3722683779853513
 1.6437402846907974
 1.6437402846907974
 1.9388834038732776
 2.8540551023207463
 2.8540551023207463
 3.2908192156173453
 3.2908192156173453
 3.339466427910192
 3.339466427910192
 3.380848336504426
 3.380848336504426
 3.9674739081053345
 3.9674739081053345
 4.2561852540977245
 4.2561852540977245
 4.382983645215763
 4.382983645215763
 5.60133468071009

In [174]:
A = randn(21, 21)
x = randn(21) + randn(21)*im
x = (randn(21) + randn(21)*im)/norm(x)

21-element Vector{ComplexF64}:
  0.008980975594788677 + 0.1515392075906423im
  0.049223502380002164 + 0.10513315469687537im
  0.040530637593051096 + 0.02309840988093394im
  -0.16622006823524996 + 0.04899802738683022im
 0.0008292385295780299 - 0.09134786388525218im
  -0.09337559625892419 - 0.0312901337929988im
  0.025414960891503136 - 0.12198875449150691im
  -0.01725936135465569 - 0.059403132035137675im
    0.0248051770552419 + 0.04892187692463558im
  -0.18381742030597528 - 0.043020998689019256im
  -0.06613485328426572 + 0.03372655149094159im
   -0.1597530078333916 + 0.07704443727447251im
   0.24543624243694045 + 0.20014103487888774im
   0.04232389189705321 + 0.22609353667993662im
 -0.019700512817616315 + 0.033598544869256786im
   0.15031809847623828 + 0.10962550003698786im
   0.18809335945945913 - 0.10623835024785366im
   0.12200892037608707 + 0.027219106074539357im
   0.12651011984642552 - 0.033745380518419514im
   0.07983186476607466 + 0.13257832375293993im
  -0.12285006805656384 - 0

In [175]:
##### Inverse Iteration

function invpower(A, sigma, x, eps)
    
    lambda = 0.0
    e = 1.0
    t = 0
    
    while (e > eps && t < 1000)
        t = t + 1
        y = (A - sigma*I)\x
        x = y/norm(y)
        lambda1 = lambda
        lambda = x'*A*x

        # Erro
        e = abs(lambda1 - lambda)
    end
    return lambda
end

invpower (generic function with 1 method)

In [178]:
invpower(A, 1.35, x, 1e-5)

0.9671646769658636 + 2.237605409072252e-6im

In [179]:
#### Comparando valores
sort(abs.(eigen(A).values))

21-element Vector{Float64}:
 0.3348409257402543
 0.3348409257402543
 0.9671640944890056
 1.2945980717661685
 1.2945980717661685
 2.9823785976328874
 2.9823785976328874
 3.150339343194169
 3.150339343194169
 3.1842374225164543
 3.1842374225164543
 3.4061964344564766
 3.561503870526764
 4.197964418472394
 4.197964418472394
 4.259054793892169
 4.259054793892169
 4.471581850858186
 4.471581850858186
 4.702073322797946
 4.702073322797946

In [191]:
# Orthogonal Iteration

function orthogonal(A, k, eps)
    
    (m, n) = size(A)
    x = randn(m, k)
    F = qr(x)
    Z = F.Q[:, 1:k]
    lambda = zeros(k)
    e = 1.0
    t = 0
    
    while (e > eps && t < 1000)
        t = t + 1
        F = qr(A*Z)
        Z = F.Q[:, 1:k]
        E = Z'*A*Z
        lambda1 = lambda
        lambda = eigen(E).values
        # Erro
        e = norm(lambda1 - lambda)
    end
    return lambda
end

orthogonal (generic function with 1 method)

In [192]:
orthogonal(A, 2, 1e-8)

2-element Vector{Float64}:
 -2.457038411959147
  2.8263197477685322

In [238]:
function qriteration(A, eps)
    
    e = 1.0
    t = 0
    
    while (e > eps && t < 10000)
        t = t + 1
        A0 = A
        A = qr(A)
        A = A.R*A.Q

        # Erro
        e = norm(A - A0)
    end
    return A
end

qriteration (generic function with 1 method)

In [241]:
A = randn(21, 21)
qriteration(A, 1e-8)

21×21 Matrix{Float64}:
  5.04182   -1.30225       …   0.678435   -0.389301    1.46588
 -1.0e-323  -4.20543           1.0228      0.0379705   0.114838
 -6.0e-323  -1.93772          -0.0255313  -0.255225    0.475401
  0.0       -0.00147497        1.25884    -0.263236    0.331587
  2.0e-323   4.77531e-210      2.05594     1.65238     0.960706
 -2.0e-323  -2.05891e-210  …   0.898311    0.67099    -0.948345
 -2.0e-323  -3.5e-323          0.70516     0.66628     1.04058
 -5.0e-323   0.0               0.662736   -0.35217     1.64477
  1.0e-323   0.0              -0.23202    -1.40473    -1.43437
  2.0e-323   0.0              -0.200603    0.606951   -0.15183
  3.0e-323   0.0           …  -1.37582     0.283016   -0.412203
  0.0        0.0               0.067622    0.0293543   0.717593
  0.0        0.0               1.21101     0.0815355  -0.957262
  0.0        0.0               0.803443   -0.572557    1.95579
  0.0        0.0              -0.871055   -0.239404    1.82701
  0.0        0.0        

In [242]:
A

21×21 Matrix{Float64}:
  0.0229609  -0.120957    1.09472    -0.526819   …   0.363628    -0.441835
  0.120502    0.846033    0.0179883  -0.650315      -0.840566     0.188444
 -0.134048    0.908667   -1.24192     0.0438599      0.572932     0.77279
  0.494251   -0.230559   -0.373694   -1.79621        1.05474     -2.00032
  0.19552     0.547927    0.265905   -0.611409      -1.94602      0.989089
  0.861298    0.268772   -1.65329     1.18424    …   0.528071    -1.15694
  1.95311    -0.230769   -0.594291    1.09416        0.589652    -1.32369
 -0.997874    0.676643    1.63987    -0.209408      -0.684407     0.518989
  0.897382    0.430319    0.104806    1.59693        0.472178    -0.0242444
 -1.66839    -0.102729   -0.575489   -1.41436        0.0769536    0.00690326
 -0.30226    -1.88487     0.980246    2.67366    …   1.06444      0.673034
  0.720195    0.544285   -0.136518    0.456942       0.752344     0.0370738
 -0.318365   -0.0869632  -1.64257    -0.139925       0.205883    -1.84123
 -0

In [260]:
function qrshiftite(A, sigma, eps)
    
    e = 1.0
    t = 0
    
    while (e > eps && t < 50000)
        t = t + 1
        F = qr(A - sigma*I)
        A0 = A
        A = F.R*F.Q + sigma*I

        # Erro
        e = norm(A - A0)
    end
    return A
end

qrshiftite (generic function with 1 method)

In [261]:
R = qrshiftite(A, 1.0, 1e-10)

21×21 Matrix{Float64}:
 -4.34568    0.460041   1.20044   …  -0.341046   -1.62229    -0.528969
 -2.0e-323  -4.11132   -2.11943       0.328263    0.336591   -0.0459389
  6.0e-323   2.35056   -3.39122       0.184605   -0.0530212  -0.464076
 -1.0e-323   0.0        0.0           0.173607   -0.585598   -1.41445
  6.0e-323   4.4e-323   1.5e-323     -0.840269   -0.518956   -1.52538
 -2.0e-323  -4.0e-323  -1.0e-323  …   0.326478   -0.610329   -1.41791
 -1.0e-323   1.0e-323   0.0           2.29083     1.37247     0.0877531
  1.0e-323   2.0e-323   5.0e-324      0.933403    0.511465    1.12492
  3.0e-323   1.0e-323   0.0           0.254007    0.0311773   2.20366
 -1.0e-323  -1.0e-323   0.0          -1.57396    -0.961652   -0.106714
  1.0e-323  -1.0e-323   0.0       …  -0.475662    0.897061   -1.43822
  1.0e-323  -1.0e-323   0.0          -0.023583    1.5039      0.51619
  0.0        0.0        0.0          -0.422669   -1.81143    -0.329997
  0.0        3.0e-323   5.0e-324      0.64796    -0.0308266

In [264]:
R[16:21, 16:21]

6×6 Matrix{Float64}:
  3.05559   1.53054    0.838473  -0.233286    0.229819   1.80494
 -2.38443   1.08994    1.64848   -0.0567858  -0.394329  -1.1194
  1.0e-323  1.0e-323   2.67462    0.124587    1.05877   -0.0507439
  0.0       0.0        3.0e-323  -1.00877     1.15915   -0.227457
  0.0       0.0        3.0e-323  -3.56396     2.0481    -0.53663
  0.0       0.0       -1.0e-323   1.5e-323   -1.0e-323   0.210197